version: 1.0.{build}
os: Visual Studio 2015
before_build:
- nuget restore
skip_tags: true
configuration: Debug
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Qujck.Core.sln
  verbosity: minimal
environment:
    COVERALLS_REPO_TOKEN:  
       secure: 8UBkBZctLBmH2IN911Q6tWJIcLaPLNIx1KvleGgKdwir6PTByCuyLERppzN2OFoi
after_test: 
  - mkdir reports
  - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -mergeoutput -register:user -target:"%xunit20%\xunit.console.x86.exe" "-targetargs:\"Qujck.Core.Tests.Unit\bin\Debug\Qujck.Core.Tests.Unit.dll\" -noshadow" -filter:"+[*]Qujck.* -[*.Tests.*]*" -output:reports\opencoverCoverage.xml
  - packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i reports\opencoverCoverage.xml --repoToken %COVERALLS_REPO_TOKEN% --commitBranch %APPVEYOR_REPO_BRANCH%
  - packages\ReportGenerator.2.3.2.0\tools\ReportGenerator.exe  -reports:"reports\opencoverCoverage.xml" -targetdir:"reports" 
  - nuget spec Qujck.Core\bin\Debug\Qujck.Core.dll
  - move Qujck.Core\bin\Debug\Qujck.Core.dll.nuspec .\
  - ren Qujck.Core.dll.nuspec Qujck.Core.nuspec
  - nuget pack